GET http://localhost:8000/api/movies
content-type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpYXQiOjE2ODU0NDEyNjMsImV4cCI6MTY4NTUwNjA2Mywicm9sZXMiOlsiUk9MRV9BRE1JTiJdLCJ1c2VybmFtZSI6ImFkbWluQGFkbWluLmNvbSJ9.i8SoGHwzBkiwrdv92TwKJErMeQYIgpHEQZZ6TOzrePqFcIL8mGuiqvG7maHWB2C1QHnZ729isf0UqUkG-6JbKOZjps8FdqpOJIN5zaicUuK1PqwdNs0GsQP8n1uAHgmZjYXEbJ_9ME8o1T1zW0BsOkbWhS4uB_eQ7wsdf2g5Ors1Cj66twO3nOCRYcz6c46mf-Yt3UcuTD5FqAdcGmzdbsyc7M7vO5K8Tt3s8kbKCJ2fhBBoq1hsmgBT9oiqNCKDlHmp0z1v3_HxNpouLAg6TTrMH4-qg8oPq4VvCZFXo5HxUB2knsjzyJpA86RdArb-s1WrsNuDrBFeYLvjC8DP9g

